---
version: '3.7'

services:
  hub:
    image: selenium/hub:3.0.1
    environment:
      GRID_BROWSER_TIMEOUT: 120000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 8000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 120000
    ports:
      - '4444:4444'

  nightwatch:
    build:
      context: .
    command: ./scripts/run_nightwatch.sh
    depends_on:
      - hub
      - node-chrome
      - node-firefox
    links:
      - node-chrome
      - node-firefox

  node-chrome:
    image: selenium/node-chrome:3.0.1
    depends_on:
      - hub
    links:
      - 'hub:hub'
    environment:
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444

  node-firefox:
    image: selenium/node-firefox:3.0.1
    depends_on:
      - hub
    links:
      - 'hub:hub'
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
